## YAML Template.
---
configuration : 
    - name : alice
      ip : 127.0.0.1
      port : 12344
      memberOf :
         - Group1
    - name : bob
      ip : 127.0.0.1
      port : 14255
      memberOf :
         - Group1
         - Group2
    - name : charlie
      ip : 127.0.0.1
      port : 12998
      memberOf :
         - Group1
         - Group2
    - name: daphnie
      ip : 127.0.0.1
      port : 1985
      memberOf :
         - Group2
    - name : ccc
      ip : 127.0.0.1
      port : 12362
      memberOf :
         - Group2
    - name : logger
      ip : 127.0.0.1
      port : 1987
    
sendRules : 
    - action : drop
      src : alice
      dest : bob
    
receiveRules :
    - action : drop
      kind : impossiblekind
